services:
  pgadmin:
    image: dpage/pgadmin4:9.9.0
    container_name: pgadmin
    restart: unless-stopped
#   ports:
#     - "8282:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.local`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
