services:
  jupyter:
    image: python-stats-alpine
    container_name: jupyter-lab
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    restart: unless-stopped
